# Generated by Django 2.2.3 on 2019-07-17 03:49

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('title', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'CREATE'), (1, 'ACCEPT'), (2, 'DENY'), (3, 'FINISH')], default=0)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactionFromUser', to='product.User')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactionToUser', to='product.User')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(2, 'BLOCK'), (0, 'REQUEST'), (1, 'ACCEPT')], default=0)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectionFromUser', to='product.User')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectionToUser', to='product.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('listUser', models.ManyToManyField(to='product.User')),
            ],
        ),
    ]
