# Generated by Django 2.2.1 on 2019-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACCEPT'), (2, 'BLOCK'), (0, 'REQUEST')], default=0),
        ),
    ]
