# Generated by Django 2.2.1 on 2019-07-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190720_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.IntegerField(choices=[(0, 'REQUEST'), (1, 'ACCEPT'), (2, 'BLOCK')], default=0),
        ),
    ]
